Repository openshift/origin-web-catalog, pull requests merged in 2018-03, with the labels that each got.

#653 Bump version to 3.9.0
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#655 Move angular-ui-router to dev dependency and bump to latest 1.0.X
  app/app.ts
  package-lock.json
  package.json
Labels: size/S

#656 Bump version to 3.10.0-alpha.0
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#657 Bug 1549450 - Better to use the same name for Clear filters, Clear Filter, Clear All Filters
  dist/origin-web-catalogs.js
  src/components/services-view/services-view.controller.ts
Labels: lgtm, size/XS

#659 Bump common version to 3.10.0-alpha.0
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/S

#658 introducing 3scale in the middleware integration list
  dist/origin-web-catalogs.js
  package-lock.json
  package.json
  src/constants.ts
Labels: lgtm, size/S

#660 Bump npm dependencies
  package-lock.json
Labels: lgtm, size/XXL

#663 Add "Virtualization" category
  dist/origin-web-catalogs.js
  src/constants.ts
Labels: size/S

#661 Remove hawtio-core dependency
  app/app.ts
  bower.json
  config/webpack.common.js
  package-lock.json
  package.json
Labels: do-not-merge/work-in-progress, size/M

#662 Bug 1449038 - Improve catalog search
  app/mockServices/mockKeywords.service.ts
  dist/origin-web-catalogs.js
  src/components/catalog-search/catalog-search.controller.ts
  src/components/services-view/services-view.controller.ts
  src/constants.ts
Labels: size/L

#665 Bump version to 3.10.0-alpha.1
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#664 Set z-index to 1040 (same as .modal-backdrop), but will still appear …
  dist/less/overlay-panel.less
  dist/origin-web-catalogs.css
  src/styles/overlay-panel.less
Labels: size/XS

#667 Bump version to v3.10.0-alpha.2
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/XS

#666 Show line separator under select-project when ordering/provisioning service catalog items
  dist/origin-web-catalogs.js
  src/components/order-service/order-service-configure.html
Labels: size/XS
