Repository openshift/origin-web-catalog, pull requests merged in 2018-02, with the labels that each got.

#638 Bug 1542669 - Don't show builder version number on first wizard page
  dist/origin-web-catalogs.js
  src/components/create-from-builder/create-from-builder-info.html
  src/components/create-from-builder/create-from-builder.html
Labels: lgtm, size/XS

#642 Check service classes to determine if template service broker is enabled
  dist/origin-web-catalogs.js
  src/services/catalog.service.ts
Labels: size/M

#643 Sort image stream tags by semantic version when possible
  app/mockServices/mockServices.module.ts
  app/mockServices/mockVersions.service.ts
  bower.json
  dist/origin-web-catalogs.js
  package-lock.json
  package.json
  src/components/create-from-builder/create-from-builder.controller.ts
  test/services-view.spec.ts
Labels: lgtm, size/XXL

#644 Bump version to 3.9.0-alpha.14
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#646 Resolve bug where repaint bug occurs in Chrome on retina displays
  dist/less/landing-page.less
  dist/origin-web-catalogs.css
  src/styles/landing-page.less
Labels: lgtm, size/XS

#647 Bump version to v3.9.0-alpha.15
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/XS

#648 Fix bug where previous Chrome repaint bug prevented Create Project fr…
  dist/less/landing-page.less
  dist/less/projects-summary.less
  dist/origin-web-catalogs.css
  src/styles/landing-page.less
  src/styles/projects-summary.less
Labels: size/S

#649 Bump version to v3.9.0-alpha.16
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#650 Use `/overview` in projectUrlFilter
  dist/origin-web-catalogs.js
  src/filters/projectUrl.ts
Labels: size/XS

#651 Remove layout.attrs as it is not in use
  bower.json
Labels: size/XS

#652 Bump version to 3.9.0-rc.0
  bower.json
  package-lock.json
  package.json
Labels: size/XS
